[workspace]
members = [
	"packages/*",
    "examples/*",
    # We have the CLI subcrates as workspace members so we can actively develop on them
    # They also can't be a workspace until nested workspaces are supported
    "examples/basic/.perseus",
    "examples/basic/.perseus/server"
]
