name: Compile and Deploy Book

on:
    push:
        paths:
            - "docs/**"
            - ".github/workflows/book.yml" # If we change this build script, it should rerun
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup mdBook
              uses: peaceiris/actions-mdbook@v1
              with:
                  mdbook-version: "latest"
            - run: cargo install bonnie
            - name: Build book
              run: bonnie docs build
            - name: Deploy book to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              if: github.ref == 'refs/heads/main'
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs/dist
